# Generated by Django 3.2.8 on 2021-10-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.TimeField(verbose_name='Horário'),
        ),
    ]
