# Generated by Django 3.2.8 on 2021-11-01 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_alter_agenda_horario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('dia', 'horario')},
        ),
    ]
