# Generated by Django 3.2.8 on 2021-11-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_alter_agenda_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Cliente atendida'),
        ),
    ]
