# Generated by Django 3.2.8 on 2021-11-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_agenda_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='status',
        ),
        migrations.AddField(
            model_name='agenda',
            name='status_atendimento',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cliente atendida'),
        ),
    ]
