# Generated by Django 3.2.8 on 2021-11-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0005_auto_20211102_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='status_atendimento',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='Cliente atendida'),
        ),
    ]
