# Generated by Django 3.2.8 on 2021-11-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0006_alter_agenda_status_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='status_atendimento',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cliente atendida'),
        ),
    ]
